services:
  ebank-database:
    container_name: ebank-database
    build:
      context: ./ebank-database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ebank-database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      ebank-network:

  ebank-user-services:
    container_name: ebank-user-services
    build: 
      context: ./ebank-backend/ebank-user-services
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ebank-database:3306/ebank-user-services-db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=ebank-user-services
      - SPRING_DATASOURCE_PASSWORD=y6qL75Nn73Dp9NgE5HPSrbbiojiiMBhNYRneqAa7
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - ebank-logs-data:/app/logs
    depends_on:
      ebank-database:
        condition: service_healthy
    networks:
      ebank-network:

  ebank-transaction-services:
    container_name: ebank-transaction-services
    build: 
      context: ./ebank-backend/ebank-transaction-services
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ebank-database:3306/ebank-transaction-services-db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=ebank-transaction-services
      - SPRING_DATASOURCE_PASSWORD=y6qL75Nn73Dp9NgE5HPSrbbiojiiMBhNYRneqAa7
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - ebank-logs-data:/app/logs
    depends_on:
      ebank-database:
        condition: service_healthy
      ebank-rate-services:
        condition: service_started
    networks:
      ebank-network:        

  ebank-rate-services:
    container_name: ebank-rate-services
    build: 
      context: ./ebank-backend/ebank-rate-services
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ebank-database:3306/ebank-rate-services-db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=ebank-rate-services
      - SPRING_DATASOURCE_PASSWORD=y6qL75Nn73Dp9NgE5HPSrbbiojiiMBhNYRneqAa7
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - ebank-logs-data:/app/logs
    depends_on:
      ebank-database:
        condition: service_healthy
    networks:
      ebank-network:

  ebank-frontend:
    container_name: ebank-frontend
    build:
      context: ./ebank-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_USER_SERVICE_URL=http://localhost:8081
      - NEXT_PUBLIC_TRANSACTION_SERVICE_URL=http://localhost:8082
      - NEXT_PUBLIC_RATE_SERVICE_URL=http://localhost:8083
    depends_on:
      - ebank-user-services
      - ebank-transaction-services
      - ebank-rate-services
    networks:
      ebank-network:

volumes:
  ebank-database-data:
    name: ebank-database-data
  ebank-logs-data:
    name: ebank-logs-data

networks:
  ebank-network:
    name: ebank-network
    driver: bridge 